### ISSUE TITLE
Send mail notifications to multiple addresses failed

### ISSUE THREAD

**Issue by zrkb** [spatie/laravel-backup#1291]
According to #743, it is possible to send mail notifications to multiple addresses setting an array instead of a string, but I've tested it and it fails miserably.

Digging through the code I found the culprit was the return type declaration for [`routeNotificationForMail()`](https://github.com/spatie/laravel-backup/blob/f15a67767b05b9d88c30120ff99b56db28b92681/src/Notifications/Notifiable.php#L11) method in the Notifiable class that only return strings.

https://github.com/spatie/laravel-backup/blob/f15a67767b05b9d88c30120ff99b56db28b92681/src/Notifications/Notifiable.php#L11

I've resolved this by making a copy of that class, removing the return type declaration, and replacing it on **backup.php** config but it will be cool if this works out the box.

**Comment by freekmurze** [comment]
This has been fixed in the latest release.

**Comment by vrusua** [comment]
Still getting the same issue for multiple addresses when trying setting them as an array instead of a string.
